# Generated by Django 5.1.6 on 2025-02-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=70)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=30)),
                ("zip", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("web", models.URLField()),
                ("age", models.PositiveIntegerField()),
            ],
        ),
    ]
